food_combo_homepage:
    pattern:  /{foodName}
    defaults: { _controller: FoodComboBundle:Default:index, foodName: _ }
    
search:
    pattern: /search/{q}
    defaults: { _controller: FoodComboBundle:Default:search, q: _ }
    
combos:
    pattern: /combos/{foodId}
    defaults: { _controller: FoodComboBundle:Default:getCombos, foodId: _ }

save:
    pattern: /combo/{food1}/{food2}
    defaults: { _controller: FoodComboBundle:Default:addCombo, food1: ~, food2: ~ }