parameters:
#    food_combo.example.class: Food\ComboBundle\Example

services:
#    food_combo.example:
#        class: %food_combo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
