<?php

namespace Food\ComboBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComboRepository extends EntityRepository
{
}
