<?php

namespace Food\ComboBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodRepository extends EntityRepository
{
	public function getLatestOne()
	{
		$query = $this->getEntityManager()
			->createQuery('
				SELECT f FROM FoodComboBundle:Food f
				ORDER BY f.id desc')
				->setMaxResults(1) ;
		
		try {
			return $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
